---
title: "El paquete Leaflet"
author: 
date: "2020-10-21"
output:
  html_document:
    theme: readable    
    toc: true
    toc_depth: 3
    toc_float:
      collapsed: false
      smooth_scroll: false    
---

```{r setup, include=FALSE}
library(knitr)

knitr::opts_chunk$set(echo = TRUE)
```


```{r message = FALSE}
library(sf)
library(dplyr)
library(leaflet)
library(dplyr)
library(tidyr)
```

```{r}
cr_cantones <- st_read(paste0("http://geos.snitcr.go.cr/be/IGN_5/wfs?", "request=GetFeature&service=WFS&version=2.0.0&typeName=IGN_5:limitecantonal_5k&outputFormat=application/json")) %>%
  st_simplify(dTolerance = 1000) %>% 
  st_transform(4326) -> sf_cantones
```


```{r}
{activos<- read.csv("https://raw.githubusercontent.com/pf0953-programaciongeoespacialr-2020/datos/master/covid19/ms/covid19-activos-cantones-20201027.csv") %>%
  pivot_longer(
  cols = c(-cod_provin, -provincia, -cod_canton, -canton), 
  names_to = "fecha", 
  values_to = "activos")
activos$fecha<- as.Date(activos$fecha, "X%d.%m.%Y")
activos <- activos %>%
  filter(fecha == max(fecha, na.rm = TRUE))}

  
{fallecidos<- read.csv("https://raw.githubusercontent.com/pf0953-programaciongeoespacialr-2020/datos/master/covid19/ms/covid19-fallecidos-cantones-20201027.csv") %>%
  pivot_longer(
    cols = c(-cod_provin, -provincia, -cod_canton, -canton), 
    names_to = "fecha", 
    values_to = "fallecidos")
fallecidos$fecha<- as.Date(fallecidos$fecha, "X%d.%m.%Y")
fallecidos <- fallecidos %>%
  filter(fecha == max(fecha, na.rm = TRUE))}

{positivos<- read.csv("https://raw.githubusercontent.com/pf0953-programaciongeoespacialr-2020/datos/master/covid19/ms/covid19-positivos-cantones-20201027.csv") %>%
  pivot_longer(
    cols = c(-cod_provin, -provincia, -cod_canton, -canton), 
    names_to = "fecha", 
    values_to = "positivos")
positivos$fecha<- as.Date(positivos$fecha, "X%d.%m.%Y")
positivos <- positivos %>%
  filter(fecha == max(fecha, na.rm = TRUE))}

{recuperados<- read.csv("https://raw.githubusercontent.com/pf0953-programaciongeoespacialr-2020/datos/master/covid19/ms/covid19-recuperados-cantones-20201027.csv") %>%
  pivot_longer(
    cols = c(-cod_provin, -provincia, -cod_canton, -canton), 
    names_to = "fecha", 
    values_to = "recuperados")
recuperados$fecha<- as.Date(recuperados$fecha, "X%d.%m.%Y")
recuperados <- recuperados %>%
  filter(fecha == max(fecha, na.rm = TRUE))}

datos <- cbind(activos, fallecidos, positivos, recuperados) %>%
  select("activos", "fallecidos", "positivos", "recuperados", "cod_canton")

df <- inner_join(sf_cantones, datos, by= c('cod_canton')) %>%
  arrange(desc(activos))
```

```{r}
df <- inner_join(sf_cantones, datos, by= c('cod_canton')) %>%
  arrange(desc(activos))
```

```{r}
bins <- c(0, 100, 500, 1000, 2000, Inf)
paleta_activos <- colorBin("YlOrRd", domain = df$activos, bins = bins)
paleta_positivos <- colorBin("YlOrRd", domain = df$positivos, bins = bins)
paleta_fallecidos <- colorBin("YlOrRd", domain = df$fallecidos, bins = bins)
paleta_recuperados <- colorBin("YlOrRd", domain = df$recuperados, bins = bins)

```

```{r}
leaflet(df) %>% 
  fitBounds(lng1 = -86, lng2 = -82, lat1 = 8, lat2 = 11) %>%
  addProviderTiles(providers$OpenStreetMap.Mapnik, group = "OpenStreetMap") %>%
  addProviderTiles(providers$Stamen.Toner, group = "StatementToner") %>%
  addProviderTiles(providers$Esri.NatGeoWorldMap, group = "NatGeoWorldMap")%>%
  addPolygons(fillColor = ~paleta_activos(activos), stroke=T, fillOpacity = 1,
              color="black", weight=0.2, opacity= 0.5,
              group = "Activos",
              popup = paste(
                "Provincia: ", df$provincia, "<br>",
                "Cant?n: ", df$canton, "<br>",
                "Activos: ", df$activos
              )
  ) %>%
  addPolygons(fillColor = ~paleta_recuperados(recuperados), stroke=T, fillOpacity = 1,
              color="black", weight=0.2, opacity= 0.5,
              group = "Recuperados",
              popup = paste(
                "Provincia: ", df$provincia, "<br>",
                "Cant?n: ", df$canton, "<br>",
                "Recuperados: ", df$recuperados
              )) %>%
  addPolygons(fillColor = ~paleta_fallecidos(fallecidos), stroke=T, fillOpacity = 1,
              color="black", weight=0.2, opacity= 0.5,
              group = "Fallecidos",
              popup = paste(
                "Provincia: ", df$provincia, "<br>",
                "Cant?n: ", df$canton, "<br>",
                "Fallecidos: ", df$fallecidos
              )) %>%
  addPolygons(fillColor = ~paleta_positivos(positivos), stroke=T, fillOpacity = 1,
              color="black", weight=0.2, opacity= 0.5,
              group = "Positivos",
              popup = paste(
                "Provincia: ", df$provincia, "<br>",
                "Cant?n: ", df$canton, "<br>",
                "Positivos: ", df$positivos
              )) %>% 
  hideGroup(c("Recuperados", "Fallecidos", "Activos")) %>%
  addLegend("bottomright", pal = paleta_activos, values = ~activos,
            title = "",
            opacity = 1
  ) %>%
  addLayersControl(
    baseGroups = c("OpenStreetMap", "StatementToner", "NatGeoWorldMap"),
    overlayGroups = c("Positivos", "Recuperados", "Fallecidos", "Activos"),
    options = layersControlOptions(collapsed = TRUE)    
  ) %>%  
  addMiniMap(
    toggleDisplay = TRUE,
    position = "bottomleft",
    tiles = providers$OpenStreetMap.Mapnik
  )
```

